[package]
name = "kove-parser"
description = "Kove's grammar: how tokens may be arranged, error recovery, and the concrete syntax tree."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reparse = { workspace = true }
kove-lexer = { workspace = true }
kove-diagnostics = { workspace = true }
